apiVersion: v1
kind: Service
metadata:
  name: {{ include "back-end.fullname" . }}
  labels:
    {{- include "back-end.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  {{ if eq .Values.service.type "LoadBalancer" }}
  {{ toYaml .Values.service.loadBalancer | nindent 2}}
  {{ end }}
  selector:
    {{- include "back-end.selectorLabels" . | nindent 4 }}