FROM golang:1.13-alpine

# Add git for fetch dependencies
RUN apk add \
        ca-certificates \
        git \
        build-base \
        --no-cache

WORKDIR /build/

# Copy Fetch dependencies
COPY go.mod go.sum ./
RUN go mod download