apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-end.fullname" . }}
data:
  config.js: |
    const config = (() => {
      return {
          "VUE_APP_API_URL": "{{ .Values.apiUrl }}",
      };
    })();