# Default values for back-end.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/todolist-app-1/back-end
  pullPolicy: IfNotPresent

imagePullSecrets: [ 
  {
    name: todolist-app-1-gke
  }
]

livenessProbePath: /todos
readinessProbePath: /todos

service:
  name: backend-end
  externalPort: 80
  internalPort: 8000
  type: LoadBalancer
  loadBalancer:
    loadBalancerIP: ""

  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: false